# Generated by Django 4.2.30 on 2026-04-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_create_moderator_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='price_at_trade',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=12),
        ),
    ]
